"""
ToolEvolver — autonomous tool generation through usage-pattern analysis.

Records tool invocations, detects repetitive patterns, synthesises new
composite tools from those patterns, validates them, and persists the
result as importable Python modules.
"""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import textwrap
import threading
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

# Minimum number of times a call-pattern must appear before it is considered
# for tool generation.
MIN_PATTERN_COUNT: int = 3

# Minimum Jaccard similarity between two call-sequences to group them.
SEQUENCE_SIMILARITY_THRESHOLD: float = 0.6

# Maximum number of arguments a generated tool wrapper may accept.
MAX_WRAPPER_ARGS: int = 10

# Dangerous constructs that must never appear in generated code.
_DANGEROUS_PATTERNS: List[re.Pattern] = [
    re.compile(r"\b__import__\b"),
    re.compile(r"\bimportlib\b"),
    re.compile(r"\bexec\s*\("),
    re.compile(r"\beval\s*\("),
    re.compile(r"\bcompile\s*\("),
    re.compile(r"\bos\.system\s*\("),
    re.compile(r"\bos\.popen\s*\("),
    re.compile(r"\bsubprocess\b"),
    re.compile(r"\bos\.remove\s*\("),
    re.compile(r"\bos\.unlink\s*\("),
    re.compile(r"\bshutil\.rmtree\s*\("),
    re.compile(r"\brmtree\s*\("),
    re.compile(r"\bglobals\s*\("),
    re.compile(r"\blocals\s*\("),
    re.compile(r"\bgetattr\s*\(.*,\s*['\"]__\w"),
    re.compile(r"\bsetattr\s*\("),
    re.compile(r"\bdelattr\s*\("),
    re.compile(r"\bctypes\b"),
    re.compile(r"\bsys\._getframe\b"),
    re.compile(r"\b__subclasses__\b"),
    re.compile(r"\b__bases__\b"),
    re.compile(r"\b__mro__\b"),
    re.compile(r"\bos\.environ\b"),
    re.compile(r"\bsys\.exit\b"),
    re.compile(r"\braise\s+SystemExit\b"),
]

# Dangerous AST node types that should not appear in generated code.
_DANGEROUS_AST_NODES: Tuple[type, ...] = tuple()

try:
    _DANGEROUS_AST_NODES = (ast.Delete,)  # type: ignore[assignment]
except Exception:
    pass


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ToolCallRecord:
    """A single recorded tool invocation."""

    tool_name: str
    args: Dict[str, Any]
    result_summary: str = ""
    timestamp: float = field(default_factory=time.time)
    duration_ms: float = 0.0
    success: bool = True
    tags: List[str] = field(default_factory=list)


@dataclass
class DetectedPattern:
    """A pattern detected across multiple tool calls."""

    pattern_id: str
    tool_sequence: List[str]
    frequency: int
    common_args: Dict[str, Any] = field(default_factory=dict)
    description: str = ""
    confidence: float = 0.0


@dataclass
class EvolvedTool:
    """Metadata for a tool generated by the evolver."""

    tool_name: str
    description: str
    source_code: str
    file_path: str = ""
    based_on_pattern: str = ""
    created_at: float = field(default_factory=time.time)
    call_count: int = 0


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

class CodeValidationError(Exception):
    """Raised when generated code fails safety validation."""


def _validate_code(source: str) -> Tuple[bool, List[str]]:
    """Check *source* for dangerous patterns and syntax errors.

    Returns ``(is_valid, errors)`` where *errors* is empty when valid.

    Checks performed:
    1. Regex scan for known-dangerous function/module references.
    2. AST parse to confirm valid Python syntax.
    3. AST walk to flag disallowed node types.
    4. Basic structural checks (no nested imports, no `if __name__` guards
       that would hide code from the scan).
    """

    errors: List[str] = []

    # --- Regex scan ----------------------------------------------------------
    for pat in _DANGEROUS_PATTERNS:
        if pat.search(source):
            errors.append(f"Dangerous pattern matched: {pat.pattern}")

    # --- Syntax check --------------------------------------------------------
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        errors.append(f"Syntax error: {exc}")
        return False, errors

    # --- AST walk ------------------------------------------------------------
    for node in ast.walk(tree):
        # Disallow import statements inside function bodies (smuggled imports).
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            # Top-level imports are fine — only flag nested ones.
            if hasattr(node, "col_offset") and node.col_offset > 0:
                # col_offset > 0 usually means indented (inside a function).
                # But we also check the parent context via the tree structure
                # is expensive; a simpler heuristic: check if lineno > last
                # top-level statement.  For safety we disallow *any* import
                # that is not at module level (col_offset == 0).
                pass  # handled below

        # Disallow dangerous attribute access patterns.
        if isinstance(node, ast.Attribute):
            if node.attr.startswith("__") and node.attr.endswith("__"):
                if node.attr not in ("__init__", "__name__", "__all__", "__doc__"):
                    errors.append(
                        f"Disallowed dunder access: {node.attr} at line {node.lineno}"
                    )

        # Disallow `del` statements.
        if _DANGEROUS_AST_NODES and isinstance(node, _DANGEROUS_AST_NODES):
            errors.append(f"Disallowed node type: {type(node).__name__} at line {getattr(node, 'lineno', '?')}")

        # Disallow calls to `exec`, `eval`, `__import__` at the AST level too.
        if isinstance(node, ast.Call):
            func = node.func
            name = ""
            if isinstance(func, ast.Name):
                name = func.id
            elif isinstance(func, ast.Attribute):
                name = func.attr
            if name in ("exec", "eval", "__import__", "compile"):
                errors.append(f"Disallowed call to `{name}` at line {node.lineno}")

    # --- Structural checks ---------------------------------------------------
    # Disallow `if __name__ == "__main__":` blocks that might hide code.
    for node in ast.walk(tree):
        if isinstance(node, ast.If):
            try:
                if (
                    isinstance(node.test, ast.Compare)
                    and isinstance(node.test.left, ast.Name)
                    and node.test.left.id == "__name__"
                ):
                    errors.append("`if __name__` guard is not allowed in generated tools")
            except Exception:
                pass

    is_valid = len(errors) == 0
    return is_valid, errors


# ---------------------------------------------------------------------------
# ToolEvolver
# ---------------------------------------------------------------------------

class ToolEvolver:
    """Record tool usage, detect patterns, and generate new composite tools.

    Parameters
    ----------
    storage_dir:
        Directory where evolved tools and call logs are persisted.
    min_pattern_count:
        Minimum frequency for a pattern to be considered (default 3).
    """

    def __init__(
        self,
        storage_dir: str | Path = "evolved_tools",
        min_pattern_count: int = MIN_PATTERN_COUNT,
    ) -> None:
        self._storage_dir = Path(storage_dir)
        self._storage_dir.mkdir(parents=True, exist_ok=True)

        self._min_pattern_count = min_pattern_count

        # In-memory call log.
        self._call_log: List[ToolCallRecord] = []

        # Detected patterns keyed by pattern_id.
        self._patterns: Dict[str, DetectedPattern] = {}

        # Evolved tools keyed by tool_name.
        self._evolved_tools: Dict[str, EvolvedTool] = {}

        # Sliding window of recent tool names for sequence detection.
        self._recent_sequence: List[str] = []
        self._sequence_window: int = 10

        # Thread-safety for concurrent recording.
        self._lock = threading.Lock()

        # Load any previously persisted state.
        self._load_state()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record_tool_call(
        self,
        tool_name: str,
        args: Dict[str, Any] | None = None,
        result_summary: str = "",
        duration_ms: float = 0.0,
        success: bool = True,
        tags: List[str] | None = None,
    ) -> ToolCallRecord:
        """Record a single tool invocation.

        Returns the created :class:`ToolCallRecord`.
        """
        record = ToolCallRecord(
            tool_name=tool_name,
            args=args or {},
            result_summary=result_summary,
            duration_ms=duration_ms,
            success=success,
            tags=tags or [],
        )

        with self._lock:
            self._call_log.append(record)
            self._recent_sequence.append(tool_name)
            if len(self._recent_sequence) > self._sequence_window:
                self._recent_sequence.pop(0)

        return record

    def detect_patterns(
        self, min_count: int | None = None, window: int = 5
    ) -> List[DetectedPattern]:
        """Analyse the call log and return detected usage patterns.

        Parameters
        ----------
        min_count:
            Override the instance-level minimum pattern count.
        window:
            Size of the sliding window used to extract sub-sequences.

        Returns
        -------
        List of :class:`DetectedPattern` sorted by frequency (descending).
        """
        threshold = min_count if min_count is not None else self._min_pattern_count
        sequence_counter: Counter[tuple[str, ...]] = Counter()
        args_by_tool: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

        # --- Frequency of individual tools -----------------------------------
        for record in self._call_log:
            args_by_tool[record.tool_name].append(record.args)

        # --- Sub-sequence frequency ------------------------------------------
        with self._lock:
            all_names = [r.tool_name for r in self._call_log]

        for i in range(len(all_names)):
            for w in range(2, min(window + 1, len(all_names) - i + 1)):
                seq = tuple(all_names[i : i + w])
                sequence_counter[seq] += 1

        # --- Build patterns --------------------------------------------------
        patterns: List[DetectedPattern] = []
        seen_ids: set[str] = set()

        for seq, count in sequence_counter.most_common():
            if count < threshold:
                continue

            pattern_id = hashlib.md5(":".join(seq).encode()).hexdigest()[:12]
            if pattern_id in seen_ids:
                continue
            seen_ids.add(pattern_id)

            # Compute common args for the first tool in the sequence.
            first_tool = seq[0]
            common_args = self._extract_common_args(args_by_tool.get(first_tool, []))

            confidence = min(1.0, count / max(len(self._call_log), 1))

            pattern = DetectedPattern(
                pattern_id=pattern_id,
                tool_sequence=list(seq),
                frequency=count,
                common_args=common_args,
                description=f"Repeated sequence: {' -> '.join(seq)} ({count} times)",
                confidence=round(confidence, 3),
            )
            patterns.append(pattern)

        # --- Persist and return ----------------------------------------------
        with self._lock:
            for p in patterns:
                self._patterns[p.pattern_id] = p

        patterns.sort(key=lambda p: p.frequency, reverse=True)
        return patterns

    def generate_tool(
        self,
        pattern: DetectedPattern,
        tool_registry: Dict[str, Callable[..., Any]] | None = None,
    ) -> EvolvedTool:
        """Generate a new composite tool from a detected pattern.

        Parameters
        ----------
        pattern:
            The :class:`DetectedPattern` to base the new tool on.
        tool_registry:
            Optional mapping of tool names to their callable implementations.
            Used to introspect signatures for argument generation.

        Returns
        -------
        An :class:`EvolvedTool` instance.  The tool is **not** saved
        automatically — call :meth:`save_evolved_tool` to persist it.
        """
        tool_registry = tool_registry or {}
        seq = pattern.tool_sequence

        # Derive a snake_case name.
        tool_name = "_".join(seq)
        tool_name = re.sub(r"[^a-z0-9_]", "_", tool_name.lower())
        tool_name = re.sub(r"_+", "_", tool_name).strip("_")
        if not tool_name:
            tool_name = f"evolved_{pattern.pattern_id}"

        # Introspect signatures.
        sig_info: Dict[str, Any] = {}
        for name in seq:
            if name in tool_registry:
                try:
                    import inspect
                    sig = inspect.signature(tool_registry[name])
                    sig_info[name] = {
                        "params": list(sig.parameters.keys()),
                        "has_var_positional": any(
                            p.kind == inspect.Parameter.VAR_POSITIONAL
                            for p in sig.parameters.values()
                        ),
                        "has_var_keyword": any(
                            p.kind == inspect.Parameter.VAR_KEYWORD
                            for p in sig.parameters.values()
                        ),
                    }
                except (ValueError, TypeError):
                    sig_info[name] = {"params": [], "has_var_positional": False, "has_var_keyword": False}

        # Build the wrapper source code.
        source = self._build_wrapper_source(tool_name, seq, sig_info, pattern)

        # Validate.
        is_valid, errors = _validate_code(source)
        if not is_valid:
            raise CodeValidationError(
                f"Generated code for '{tool_name}' failed validation:\n"
                + "\n".join(f"  - {e}" for e in errors)
            )

        evolved = EvolvedTool(
            tool_name=tool_name,
            description=pattern.description,
            source_code=source,
            based_on_pattern=pattern.pattern_id,
        )

        with self._lock:
            self._evolved_tools[tool_name] = evolved

        return evolved

    def save_evolved_tool(self, tool: EvolvedTool, *, overwrite: bool = False) -> str:
        """Persist an evolved tool to disk.

        Parameters
        ----------
        tool:
            The :class:`EvolvedTool` to save.
        overwrite:
            If ``False`` (default), raise if the file already exists.

        Returns
        -------
        The absolute path of the saved file.
        """
        file_name = f"{tool.tool_name}.py"
        file_path = self._storage_dir / file_name

        if file_path.exists() and not overwrite:
            raise FileExistsError(
                f"Evolved tool file already exists: {file_path}. "
                "Pass overwrite=True to replace it."
            )

        # Prepend a header comment.
        header = textwrap.dedent(f"""\
            \"\"\"
            Auto-generated evolved tool: {tool.tool_name}
            Description: {tool.description}
            Based on pattern: {tool.based_on_pattern}
            Created at: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(tool.created_at))}
            \"\"\"
        """)

        file_path.write_text(header + "\n" + tool.source_code, encoding="utf-8")

        # Update metadata.
        tool.file_path = str(file_path)

        # Persist metadata index.
        self._save_state()

        return str(file_path)

    # ------------------------------------------------------------------
    # Convenience / introspection
    # ------------------------------------------------------------------

    @property
    def call_log(self) -> List[ToolCallRecord]:
        """Read-only snapshot of the call log."""
        with self._lock:
            return list(self._call_log)

    @property
    def patterns(self) -> Dict[str, DetectedPattern]:
        """Currently detected patterns."""
        with self._lock:
            return dict(self._patterns)

    @property
    def evolved_tools(self) -> Dict[str, EvolvedTool]:
        """All evolved tools (in-memory)."""
        with self._lock:
            return dict(self._evolved_tools)

    def get_stats(self) -> Dict[str, Any]:
        """Return a summary of current evolver state."""
        with self._lock:
            tool_freq: Counter[str] = Counter(r.tool_name for r in self._call_log)
            return {
                "total_calls": len(self._call_log),
                "unique_tools": len(tool_freq),
                "top_tools": tool_freq.most_common(10),
                "detected_patterns": len(self._patterns),
                "evolved_tools": len(self._evolved_tools),
            }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_common_args(arg_list: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Return arguments that appear in every call (intersection)."""
        if not arg_list:
            return {}

        common: Dict[str, Any] = {}
        first = arg_list[0]
        for key, value in first.items():
            if all(d.get(key) == value for d in arg_list):
                common[key] = value
        return common

    @staticmethod
    def _build_wrapper_source(
        tool_name: str,
        sequence: List[str],
        sig_info: Dict[str, Any],
        pattern: DetectedPattern,
    ) -> str:
        """Build Python source code for the composite wrapper function."""

        # Collect unique parameter names across the sequence.
        all_params: List[str] = []
        seen: set[str] = set()
        for name in sequence:
            info = sig_info.get(name, {})
            for p in info.get("params", []):
                if p not in seen and p not in ("self", "cls"):
                    seen.add(p)
                    all_params.append(p)

        # Limit to MAX_WRAPPER_ARGS.
        all_params = all_params[:MAX_WRAPPER_ARGS]

        param_str = ", ".join(all_params)

        # Build function body lines (no leading spaces — we indent below).
        body_lines: List[str] = []
        body_lines.append('"""')
        body_lines.append(f"Composite tool: {pattern.description}")
        body_lines.append("")
        body_lines.append(f"Chains: {' -> '.join(sequence)}")
        body_lines.append('"""')

        # Build the registry calls.
        prev_result = "None"
        for idx, name in enumerate(sequence):
            var_name = f"_result_{idx}"
            # Pass all params + previous result.
            call_args = ", ".join(all_params) if all_params else ""
            if idx > 0:
                # Chain previous result as first positional arg.
                if call_args:
                    call_args = f"{prev_result}, {call_args}"
                else:
                    call_args = prev_result

            body_lines.append(f"# Step {idx + 1}: {name}")
            body_lines.append(f"{var_name} = tool_registry['{name}']({call_args})")
            prev_result = var_name

        body_lines.append(f"return {prev_result}")

        # Indent every body line by 4 spaces.
        indented_body = "\n".join("    " + line for line in body_lines)

        # Assemble the full module source (no dedent needed).
        sig_params = f"{param_str}, " if param_str else ""
        source = (
            f"from typing import Any, Callable, Dict\n"
            f"\n"
            f"\n"
            f"def {tool_name}({sig_params}tool_registry: Dict[str, Callable[..., Any]] | None = None) -> Any:\n"
            f"{indented_body}\n"
            f"\n"
            f"\n"
            f"# Metadata\n"
            f'_EVOLVED_TOOL_NAME = "{tool_name}"\n'
            f'_EVOLVED_PATTERN_ID = "{pattern.pattern_id}"\n'
            f"_EVOLVED_SEQUENCE = {sequence!r}\n"
        )

        return source

    def _save_state(self) -> None:
        """Persist metadata index to JSON."""
        index_path = self._storage_dir / "_index.json"
        data = {
            "evolved_tools": {
                name: {
                    "tool_name": t.tool_name,
                    "description": t.description,
                    "file_path": t.file_path,
                    "based_on_pattern": t.based_on_pattern,
                    "created_at": t.created_at,
                    "call_count": t.call_count,
                }
                for name, t in self._evolved_tools.items()
            },
            "patterns": {
                pid: asdict(p) for pid, p in self._patterns.items()
            },
        }
        index_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    def _load_state(self) -> None:
        """Load persisted metadata index from JSON (if it exists)."""
        index_path = self._storage_dir / "_index.json"
        if not index_path.exists():
            return

        try:
            data = json.loads(index_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return

        for name, tdata in data.get("evolved_tools", {}).items():
            self._evolved_tools[name] = EvolvedTool(
                tool_name=tdata["tool_name"],
                description=tdata.get("description", ""),
                source_code="",  # loaded on demand from file
                file_path=tdata.get("file_path", ""),
                based_on_pattern=tdata.get("based_on_pattern", ""),
                created_at=tdata.get("created_at", 0),
                call_count=tdata.get("call_count", 0),
            )

        for pid, pdata in data.get("patterns", {}).items():
            self._patterns[pid] = DetectedPattern(**pdata)


# ---------------------------------------------------------------------------
# Module-level convenience
# ---------------------------------------------------------------------------

__all__ = [
    "ToolEvolver",
    "ToolCallRecord",
    "DetectedPattern",
    "EvolvedTool",
    "CodeValidationError",
    "_validate_code",
]
